fix(preload): Avoid mysterious binding.unlink error message.
If the state file cannot be written, the error causes the process to exit
and the exit event processor reports eg
fs.js:1061
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'undefined/258755'
followed by a stacktrace.

To avoid this, don't add the handler until we succeed at saving the state file.
Also print the error from saving so the user can know something went wrong.